name: eurydice-backend
services:

  db:
    container_name: eurydice-database
    image: postgres:17.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  db_monitoring:
    container_name: eurydice-db-monitoring
    image: adminer:5.4.1
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    container_name: eurydice-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    environment:
      DB_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    

volumes:
  db_data:
    name: eurydice-db-data
